## GitHub Actions を使用して、毎日定期的に百度（Baidu）へリンクをプッシュし、インデックス登録率を向上させます ##

name: pushUrl

# 2つのトリガー方法：1. コードのプッシュ時、2. 毎日 23:00 UTC（日本時間 08:00）に実行
on:
  push:
  schedule:
    - cron: '0 23 * * *' # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '無条件で URL をプッシュする'
        type: boolean
        required: true
        default: true

# on:
  # schedule:
  #   - cron: '*/5 * * * *' # 5分ごとに実行（テスト用）

jobs:
  bot:
    runs-on: ubuntu-latest # 最新版の Ubuntu で実行

    steps:
      - name: 'Checkout codes' # ステップ 1: リポジトリのコードを取得
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install requests
        run: pip install requests

      - name: Push
        env:
          URL: ${{ secrets.URL }}
          BAIDU_TOKEN: ${{ secrets.BAIDU_TOKEN }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: |
          if [ -n "$URL" ]; then
            if [ -n "$BAIDU_TOKEN" ]; then
              python pushUrl.py --url $URL --baidu_token $BAIDU_TOKEN
            else
              echo "Github Action Secrets で BAIDU_TOKEN を設定してください:"
              echo "詳細はこちらを参照: 'https://www.ghlcode.cn/fe032806-5362-4d82-b746-a0b26ce8b9d9'"
            fi
            if [ -n "$BING_API_KEY" ]; then
              python pushUrl.py --url $URL --bing_api_key $BING_API_KEY
            else
              echo "Github Action Secrets で BING_API_KEY を設定してください:"
              echo "詳細はこちらを参照: 'https://www.ghlcode.cn/fe032806-5362-4d82-b746-a0b26ce8b9d9'"
            fi
          else
            echo "Github Action Secrets で URL を設定してください:"
            echo "詳細はこちらを参照: 'https://www.ghlcode.cn/fe032806-5362-4d82-b746-a0b26ce8b9d9'"
          fi
